### ISSUE TITLE
The content of `modules/past-exams` folder should be moved to appropriate module directories

### ISSUE THREAD

**Issue by sglavoie** [world-class/binary-assets#7]
## Acceptance

* [ ] The content of `modules/past-exams` has been moved to the relevant modules folders inside `modules/`.
* [ ] Links have been updated in the REPL (pointing to the directories and no specific files if that was the case).

## Tasks

* [ ] Move content from `modules/past-exams` to the concerned modules (e.g. `modules/cm3005-ds`).
* [ ] Update relevant links that will break in the REPL.
